### ISSUE TITLE
Jupyter Container exited with code 3

### ISSUE THREAD

**Issue by MLHafizur** [PacktPublishing/Machine-Learning-Engineering-with-MLflow#12]
Chapter: 4 | MLFlow and Postgresql containers are running as expected, But the Jupyter container exited.

Here are the logs of the container:

Entered start.sh with args: jupyter lab
Updated the jovyan user:
- username: jovyan       -> 
- home dir: /home/jovyan -> /home/
id: ‘’: no such user
id: ‘’: no such user
Update 's UID:GID to :100
id: ‘’: no such user
groupadd: '' is not a valid group name

Eagerly waiting for your response:

**Comment by webmakaka** [comment]
Hi!
Is it still actual for you? (I think no)
I updated codes and run chapter 4 without critical errors. Everything works.
https://github.com/webmakaka/Machine-Learning-Engineering-with-MLflow

**Comment by nlauchande** [comment]
Fixes for @webmakaka : Being worked on this https://github.com/PacktPublishing/Machine-Learning-Engineering-with-MLflow/pulls
