### ISSUE TITLE
[Chapter 09] Where is the Dockerfile for pystock-inference-api ?

### ISSUE THREAD

**Issue by webmakaka** [PacktPublishing/Machine-Learning-Engineering-with-MLflow#17]
```
The code required for this section is in the pystock-inference-api folder .
```

Can't find

https://github.com/PacktPublishing/Machine-Learning-Engineering-with-MLflow/tree/master/Chapter09/psystock-inference-api

**Comment by nlauchande** [comment]
@webmakaka: This section in particular didn't contain any docker file. If i remember correctly, at this point we assume that the reader would be quite familiar with the details of the docker image and we will focus on the docker file.
