### ISSUE TITLE
Running a MLflow project with docker_env fails to create the docker container.

### ISSUE THREAD

**Issue by d4nielmeyer** [PacktPublishing/Machine-Learning-Engineering-with-MLflow#3]
### **Details**
- **Code (cloned the repo as instructed):** https://github.com/PacktPublishing/Machine-Learning-Engineering-with-MLflow/tree/master/Chapter01/stockpred
- **OS Platform and Distribution:** Windows 11
- **MLflow installed from (source or binary):** pip install mlflow
MLflow version (run mlflow --version): 1.6
- **Python version:** 3.8.8
- **Exact command to reproduce:** mlflow run .
- **Describe the problem:** The MLflow project using a docker_env and run with above command throws a docker error.
- **Expected behavior:** Python file is executed and tracked and run is added in mlruns.
- **Actual behavior:** docker throws an error --> `docker: Error response from daemon: invalid mode: \Users\Daniel\Machine-Learning-Engineering-with-Mlflow\Chapter01\stockpred\mlruns\0\d522ee8e9d334a48b362f23925c90150\artifacts.`

The problem seems to be that mlflow tries passes a -v flag to docker to map a host directory to itself:

`docker run --rm -v C:\Users\Daniel\Machine-Learning-Engineering-with-Mlflow\Chapter01\stockpred\mlruns:/mlflow/tmp/mlruns 
**-v C:\Users\Daniel\Machine-Learning-Engineering-with-Mlflow\Chapter01\stockpred\mlruns\0\d522ee8e9d334a48b362f23925c90150\artifacts:C:\Users\Daniel\Machine-Learning-Engineering-with-Mlflow\Chapter01\stockpred\mlruns\0\d522ee8e9d334a48b362f23925c90150\artifacts** 
-e MLFLOW_RUN_ID=d522ee8e9d334a48b362f23925c90150 -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 stockpred:f32b72e python train.py' in run with ID 'd522ee8e9d334a48b362f23925c90150`

### **Other info / logs**
`Daniel@mm1-T480-0518-4 MINGW64 ~/Machine-Learning-Engineering-with-Mlflow/Chapter01/stockpred (master)
$ mlflow run .`

`2021/11/02 17:50:28 INFO mlflow.projects.docker: === Building docker image stockpred:f32b72e ===`

`2021/11/02 17:50:29 INFO mlflow.projects.docker: Temporary docker context file C:\Users\Daniel\AppData\Local\Temp\tmpaseubm0i was not deleted.`

`2021/11/02 17:50:29 INFO mlflow.projects.utils: === Created directory C:\Users\Daniel\AppData\Local\Temp\tmpazdbdi5b for downloading remote URIs passed to arguments of type 'path' ===`

`2021/11/02 17:50:29 INFO mlflow.projects.backend.local: === Running command 'docker run --rm -v C:\Users\Daniel\Machine-Learning-Engineering-with-Mlflow\Chapter01\stockpred\mlruns:/mlflow/tmp/mlruns -v C:\Users\Daniel\Machine-Learning-Engineering-with-Mlflow\Chapter01\stockpred\mlruns\0\d522ee8e9d334a48b362f23925c90150\artifacts:C:\Users\Daniel\Machine-Learning-Engineering-with-Mlflow\Chapter01\stockpred\mlruns\0\d522ee8e9d334a48b362f23925c90150\artifacts -e MLFLOW_RUN_ID=d522ee8e9d334a48b362f23925c90150 -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 stockpred:f32b72e python train.py' in run with ID 'd522ee8e9d334a48b362f23925c90150' ===
docker: Error response from daemon: invalid mode: \Users\Daniel\Machine-Learning-Engineering-with-Mlflow\Chapter01\stockpred\mlruns\0\d522ee8e9d334a48b362f23925c90150\artifacts.
See 'docker run --help'.
2021/11/02 17:50:30 ERROR mlflow.cli: === Run (ID 'd522ee8e9d334a48b362f23925c90150') failed ===`

**Comment by nlauchande** [comment]
@d4nielmeyer: Thanks for reporting. I spent some time looking at possible issues :

1. Is your file system mountable in docker. I would assume it's enabled by default in Windows - https://docs.docker.com/desktop/windows/ - You can look at file-sharing here.

2. Most of the development was done on a bash environment and tested on a Windows environment on the Ubuntu subsystem mode, can you confirm whether you tested in the Ubuntu subsystem. It might be a conflict on path formats.

**Comment by nlauchande** [comment]
Onn a future edition we will consider proper Windows Subsystem testing . It was not considered in the first edition.
