### ISSUE TITLE
Chapter 7 `mlflow run . --experiement-name=psystock_data_pipelines` fails - BUGFIX

### ISSUE THREAD

**Issue by hdotking** [PacktPublishing/Machine-Learning-Engineering-with-MLflow#7]
## Instructions 
Page 133 of chapter 7 requires the reader to navigate to the following directory and enter the commands below:

`cd Chapter07/psystock-data-features-main`
 `mlflow run . --experiement-name=psystock_data_pipelines`

## Problem

The following error message appears when running line of code specified above:
``` 
Traceback (most recent call last):
  File "feature_set_generation.py", line 30, in <module>
    raise Exception('x should not exceed 5. The value of x was: {}'.format(x))
NameError: name 'x' is not defined
```

## Solution
Resolve this by deleting line 30 below in `feature_set_generation.py`

`30         raise Exception('x should not exceed 5. The value of x was: {}'.format(x))`
The stray `raise` statement is referencing an undefined variable `x`.

Removing this line of code removed the reference to this point and lead to the successful deployment of the experiment. I would consider adding such assertions in the `check_verify_data.py` file instead.

**Comment by nlauchande** [comment]
Thanks, invaluable contributions. We will add this to the Errata!!!
